export enum Utils {
    HOLDER_SEARCH = "UTILS.HOLDER_SEARCH",
    TITLE_SUCCESS = "UTILS.TITLE_SUCCESS",
    TITLE_ERROR = "UTILS.TITLE_ERROR",
    TITLE_CONFIRM = "UTILS.TITLE_CONFIRM",
    TITLE_CANCEL = "UTILS.TITLE_CANCEL",
    MESSAGE_AMOUNT_ERROR = "UTILS.AMOUNT_ERROR",
    MESSAGE_CREATE_SUCCESS = "Created data successfully",
    MESSAGE_UPDATE_SUCCESS = "Updated data successfully",
    MESSAGE_DELETE_SUCCESS = "Deleted data successfully",
    MESSAGE_VALID_REQUIRE = "Please fill required fields",
    MESSAGE_CONFIRM_DELETE = "Are you sure you want to delete this item?",
    MESSAGE_CONFIRM = "Are you sure you want to confirm this user?",    
    MESSAGE_File_REQUIRE = "This file is required",
    SEARCH = "UTILS.SEARCH",
    MESSAGE_REPLY_EMAIL_SUCCESS = "UTILS.MESSAGE_REPLY_EMAIL_SUCCESS",
    OK = "UTILS.OK",
    CLOSE = "UTILS.CLOSE",
    DOWNLOAD = "UTILS.DOWNLOAD",
    SAVE = "UTILS.SAVE",
    STATUS_NEW = "New",
    STATUS_CLOSE = "Pair success",
    STATUS_CANCEL = "Cancel",
    STATUS_EXPIRED = "Expiried",
    STATUS_WAITTING = "Waitting",
    TYPE_LEAGUE_ROUND_CIRCLE = "Round Circle",
    TYPE_LEAGUE_TWO_STAGES = "Two Stages"
}