// ACTION LOGIN 
export const IS_LOGIN = 'IS_LOGIN';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const IS_REGISTER = 'IS_REGISTER';
export const REGISTER_SUCCESSFULLY = 'REGISTER_SUCCESSFULLY';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const IS_FORGOT_PASS = 'IS_FORGOT_PASS';
export const FORGOT_PASS_SUCCESSFULLY = 'FORGOT_PASS_SUCCESSFULLY';
export const FORGOT_PASS_FAILED = 'FORGOT_PASS_FAILED';

export const IS_UPDATE_INFO = 'IS_UPDATE_INFO';
export const UPDATE_INFO_SUCCESSFULLY = 'UPDATE_INFO_SUCCESSFULLY';
export const UPDATE_INFO_FAILED = 'UPDATE_INFO_FAILED';

export const IS_CHANGE_PASS = 'IS_CHANGE_PASS';
export const CHANGE_PASS_SUCCESSFULLY = 'CHANGE_PASS_SUCCESSFULLY';
export const CHANGE_PASS_FAILED = 'CHANGE_PASS_FAILED';
