import {
    IS_GET_LIST_TEAM,
    GET_LIST_TEAM_SUCCESSFULLY,
    GET_LIST_TEAM_FAILED,

    IS_CREATE_TEAM,
    CREATE_TEAM_SUCCESSFULLY,
    CREATE_TEAM_FAILED,

    IS_UPDATE_TEAM,
    UPDATE_TEAM_SUCCESSFULLY,
    UPDATE_TEAM_FAILED,

    IS_ADD_MEMBER_TEAM,
    ADD_MEMBER_TEAM_SUCCESSFULLY,
    ADD_MEMBER_TEAM_FAILED,

    IS_DEL_MEMBER_TEAM,
    DEL_MEMBER_TEAM_SUCCESSFULLY,
    DEL_MEMBER_TEAM_FAILED,


    IS_DEL_TEAM,
    DEL_TEAM_SUCCESSFULLY,
    DEL_TEAM_FAILED,

    IS_GET_DETAIL_TEAM,
    GET_DETAIL_TEAM_SUCCESSFULLY,
    GET_DETAIL_TEAM_FAILED,
} from './ActionTypes';

export const isregister = (value) => {
    return {
        type: IS_REGISTER,
        isLoading: true,
        value,
    };
}

